dependencies:
  - python=3.5
  - pip:
    - box2d-py==2.3.*
    - "--editable=git+https://github.com/openai/gym.git#egg=gym"
    - "--editable=git+https://github.com/openai/baselines.git#egg=baselines"
    - jupyter==1.0.*
    - jupyter_contrib_nbextensions==0.5.*
    - numpy==1.15.*
    - seaborn==0.9.*
    - pandas==0.23.*
